package main

import (
	"bufio"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	modulePathRe = regexp.MustCompile(`^module\s+(\S+)`)
	goVersionRe  = regexp.MustCompile(`^go\s+(\d+\.\d+(?:\.\d+)?)`)
)

// syntheticGoWork returns a generated go.work covering every module under root, for roots that
// hold several modules but no go.work of their own (e.g. a directory of checked-out repos).
// Without it gopls loads each module separately, which breaks cross-module navigation and fails
// outright when nested go.work files lack a go directive. Returns "" when not needed.
func syntheticGoWork(id, root string) string {
	for _, f := range []string{"go.work", "go.mod"} {
		if _, err := os.Stat(filepath.Join(root, f)); err == nil {
			return ""
		}
	}
	type mod struct{ dir, path, goVer string }
	var mods []mod
	_ = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			name := d.Name()
			depth := strings.Count(strings.TrimPrefix(path, root), string(filepath.Separator))
			if path != root && (alwaysSkip[name] || strings.HasPrefix(name, ".") || name == "vendor" || name == "testdata" || depth > 4) {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Name() == "go.mod" && inGitRepo(root, filepath.Dir(path)) {
			if m, ok := readGoMod(path); ok {
				mods = append(mods, mod{filepath.Dir(path), m[0], m[1]})
			}
		}
		return nil
	})
	if len(mods) < 2 {
		return ""
	}
	// A module path may appear more than once (copies of a repo); keep the shallowest.
	sort.Slice(mods, func(i, j int) bool {
		di, dj := strings.Count(mods[i].dir, "/"), strings.Count(mods[j].dir, "/")
		if di != dj {
			return di < dj
		}
		return mods[i].dir < mods[j].dir
	})
	seen := map[string]bool{}
	goVer := "1.21"
	var b strings.Builder
	for _, m := range mods {
		if seen[m.path] {
			continue
		}
		seen[m.path] = true
		if versionLess(goVer, m.goVer) {
			goVer = m.goVer
		}
		fmt.Fprintf(&b, "\t%s\n", m.dir)
	}
	dir := filepath.Join(os.Getenv("HOME"), ".cache", "codebrowse", "gowork", id)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return ""
	}
	path := filepath.Join(dir, "go.work")
	content := fmt.Sprintf("// Generated by codebrowse for %s; do not edit.\ngo %s\n\nuse (\n%s)\n", root, goVer, b.String())
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return ""
	}
	return path
}

func readGoMod(path string) ([2]string, bool) {
	f, err := os.Open(path)
	if err != nil {
		return [2]string{}, false
	}
	defer f.Close()
	var res [2]string
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if m := modulePathRe.FindStringSubmatch(line); m != nil {
			res[0] = m[1]
		} else if m := goVersionRe.FindStringSubmatch(line); m != nil {
			res[1] = m[1]
		}
	}
	return res, res[0] != ""
}

// versionLess compares dotted Go versions like "1.21" and "1.27.1".
func versionLess(a, b string) bool {
	pa, pb := strings.Split(a, "."), strings.Split(b, ".")
	for i := 0; i < max(len(pa), len(pb)); i++ {
		var x, y int
		if i < len(pa) {
			fmt.Sscan(pa[i], &x)
		}
		if i < len(pb) {
			fmt.Sscan(pb[i], &y)
		}
		if x != y {
			return x < y
		}
	}
	return false
}

// inGitRepo reports whether dir is inside a git checkout below root. Modules outside any checkout
// (unpacked source dumps, vendored copies) are left out to keep gopls fast.
func inGitRepo(root, dir string) bool {
	for d := dir; strings.HasPrefix(d, root); d = filepath.Dir(d) {
		if _, err := os.Stat(filepath.Join(d, ".git")); err == nil {
			return true
		}
		if d == root {
			break
		}
	}
	return false
}
