package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// savedTour is a walkthrough generated by `codebrowse tour`, kept so the UI can list it.
type savedTour struct {
	ID      string    `json:"id"`
	Title   string    `json:"title"`
	Project string    `json:"project"`
	Steps   int       `json:"steps"`
	Created time.Time `json:"created"`
	Encoded string    `json:"encoded"` // the value of #tour=
}

func toursDir(cfg *config) string {
	return filepath.Join(filepath.Dir(cfg.path), "tours")
}

func saveTour(cfg *config, t *tour, encoded string) (string, error) {
	dir := toursDir(cfg)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	now := time.Now()
	id := fmt.Sprintf("%s-%s", now.Format("20060102-150405"), slugify(t.Title))
	st := savedTour{ID: id, Title: t.Title, Project: t.Project, Steps: len(t.Steps), Created: now, Encoded: encoded}
	data, err := json.MarshalIndent(st, "", "  ")
	if err != nil {
		return "", err
	}
	return id, os.WriteFile(filepath.Join(dir, id+".json"), data, 0o600)
}

func listTours(cfg *config) []savedTour {
	files, _ := filepath.Glob(filepath.Join(toursDir(cfg), "*.json"))
	res := []savedTour{}
	for _, f := range files {
		data, err := os.ReadFile(f)
		if err != nil {
			continue
		}
		var st savedTour
		if json.Unmarshal(data, &st) == nil && st.Encoded != "" {
			res = append(res, st)
		}
	}
	sort.Slice(res, func(i, j int) bool { return res[i].Created.After(res[j].Created) })
	return res
}

func (s *server) handleTours(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, listTours(s.cfg))
}

func (s *server) handleDeleteTour(w http.ResponseWriter, r *http.Request) {
	id := r.FormValue("id")
	if id == "" || strings.ContainsAny(id, `/\`) || strings.HasPrefix(id, ".") {
		httpErr(w, http.StatusBadRequest, errors.New("bad id"))
		return
	}
	if err := os.Remove(filepath.Join(toursDir(s.cfg), id+".json")); err != nil {
		httpErr(w, http.StatusNotFound, err)
		return
	}
	writeJSON(w, map[string]bool{"ok": true})
}
